[tool.poetry]
name = "nr_all"
version = "1.0.0a1"
description = "Czech National Repository index that store all records from all metadata models"
authors = ["Daniel Kopecký <Daniel.Kopecky@techlib.cz>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pytest-cov = "^2.10.1"
oarepo = "^3.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
